name: unfocuser
description: "A Widget to pop the keyboard when removing focus from inputs."
version: 1.0.0
repository: https://github.com/hanskokx/unfocuser
issue_tracker: https://github.com/hanskokx/unfocuser/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
